global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "demo_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "ski-rental:8080",
            "notification-service:8083",
            "analytics-service:8082",
            "payment-service:8085",
          ]
